### ISSUE TITLE
On a new install tests do not run

### ISSUE THREAD

**Issue by devingray** [laravel-presets/pest#1]
I get No tests executed! 
 when it should atleast run the example tests

**Comment by innocenzi** [comment]
Hello, I'm not sure what you mean. Can you provide more information, like the console logs? 

The preset installs Pest, but it doesn't run the tests. Your existing PHPUnit tests are not converted to Pest (you can try [drift](https://github.com/pestphp/drift) for that), but they can still be run with Pest with either `php artisan test` or `./vendor/bin/pest`. 

Make sure to [follow the docs](https://pestphp.com/docs/writing-tests): your test files must end with `Test.php`.

**Comment by devingray** [comment]
When I install it, it installs pest great.. 

I still have the default laravel tests `ExampleTest.php` 

I run `php artisan test` and no tests are executed. 

I can do extra steps to get it working but thought you should know 💯

**Comment by innocenzi** [comment]
Can you screenshot your file hierarchy, and share your console logs and `composer.json`? 

With the default tests, it should definitely work.

https://github.com/laravel-presets/pest/runs/1450752985?check_suite_focus=true

![](https://i.imgur.com/i0Q6RUy.png)

**Comment by devingray** [comment]
Ok, let me try it again

**Comment by devingray** [comment]
I have created a gif for you for two reasons. 

1. It was fun and I never get to use my gif tool
2. It shows that a brand new install does not work. 

I will have some time over the weekend to potentially submit a PR

![pest](https://user-images.githubusercontent.com/11573528/100335894-12e80800-3008-11eb-9e62-081fa5468b88.gif)

**Comment by innocenzi** [comment]
Interesting. I never used the Laravel installer, I'll check when I can. I don't think it's related to the preset though: 
- Can you run `php artisan test` without running the preset? Does it work?
- If it does work, can you run `npx use-preset laravel:pest -v` and show me the logs?
- What does `./vendor/bin/pest` outputs?

**Comment by innocenzi** [comment]
Just tested this out on my Windows machine. `php artisan test` works before and after installing the preset. And I used both `laravel new` and `composer create-project laravel/laravel` to test.

**Comment by devingray** [comment]
Hmm, I will have to find the root cause, but since it's working for you we can close this. If I do find out what's happening I'll PR a fix incase another gets same. But possible to be my machine only

**Comment by innocenzi** [comment]
Alright. Even of it's not something you can PR I'm interested in the cause too, so feel free to comment again here if you find an explanation. :)

**Comment by devingray** [comment]
I found it. 

Issue was that I was using the PHP version from Macos instead of the `brew install` version. 


`brew unlink php && brew link php` 💯
